name = "dario"
license = "MIT"
description = "A Hugo theme inspired by Dario Amodei's personal website"
licenselink = "https://github.com/grantbirki/dario/blob/main/LICENSE"
homepage = "https://dario.birkio.io"

tags = [
  "responsive",
  "simple",
  "clean",
  "light",
  "dark",
  "blog",
  "minimalist"
]

features = [
  "responsive",
  "blog",
  "opengraph",
  "favicon",
  "theme-toggle"
]

[author]
  name = "Grant Birkinbine"
  homepage = "https://github.com/grantbirki"

min_version = "0.119.0"
