name: deploy

on:
  push:
    paths-ignore:
      - "LICENSE"
      - "README.md"
      - ".gitignore"
    branches:
      - main
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deployment-check:
    runs-on: ubuntu-latest
    outputs: # set outputs for use in downstream jobs
      continue: ${{ steps.deployment-check.outputs.continue }}

    steps:
      # https://github.com/github/branch-deploy/blob/d3c24bd92505e623615b75ffdfac5ed5259adbdb/docs/merge-commit-strategy.md
      - name: deployment check
        uses: github/branch-deploy@v10
        id: deployment-check
        with:
          merge_deploy_mode: "true"
          environment: github-pages

  build:
    if: ${{ needs.deployment-check.outputs.continue == 'true' }}
    needs: deployment-check
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set hugo version
        id: hugo-version
        run: |
          HUGO_VERSION=$(cat .hugo-version)
          echo "HUGO_VERSION=${HUGO_VERSION}" >> $GITHUB_OUTPUT

      - name: install vendored hugo cli
        env:
          HUGO_VERSION: ${{ steps.hugo-version.outputs.HUGO_VERSION }}
        run: sudo dpkg -i vendor/hugo_extended_${HUGO_VERSION}_linux-amd64.deb

      - name: setup pages
        id: pages
        uses: actions/configure-pages@v5.0.0

      - name: build with hugo
        run: hugo --gc --logLevel info --baseURL ${{ steps.pages.outputs.base_url }}

      - name: write build version
        run: echo ${GITHUB_SHA} > ./public/version.txt

      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    if: ${{ needs.deployment-check.outputs.continue == 'true' }}
    needs: [ deployment-check, build ]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
